import Link from "next/link";

export const metadata = { title: "Terms of Service — Metalyzi" };

export default function TermsOfServicePage() {
  return (
    <div className="mx-auto max-w-4xl px-6 py-16">
      <h1 className="mb-8 text-3xl font-bold text-foreground">
        Terms of Service
      </h1>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Last updated: 4 April 2026
      </p>

      {/* 1. Introduction */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        1. Introduction and Acceptance of Terms
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Welcome to Metalyzi. These Terms of Service (&quot;Terms&quot;) govern
        your access to and use of the Metalyzi platform, including our website
        at{" "}
        <a
          href="https://www.metalyzi.co.uk"
          className="text-primary underline hover:text-primary/80"
          target="_blank"
          rel="noopener noreferrer"
        >
          www.metalyzi.co.uk
        </a>
        , applications, tools, reports, and all related services (collectively,
        the &quot;Service&quot;). By accessing or using the Service, you agree to
        be bound by these Terms. If you do not agree, you must not use the
        Service.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        These Terms constitute a legally binding agreement between you and Metusa
        Property Ltd, trading as Metalyzi. Please read them carefully before
        using the Service.
      </p>

      {/* 2. About Us */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        2. About Us
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Metalyzi is a trading name of Metusa Property Ltd, a company registered
        in England and Wales under company number 15651934. Our registered office
        is at 9D Worrall Street, Salford, Manchester, M5 4TZ, United Kingdom.
        You can contact us at{" "}
        <a
          href="mailto:contact@metalyzi.co.uk"
          className="text-primary underline hover:text-primary/80"
        >
          contact@metalyzi.co.uk
        </a>{" "}
        or by telephone at{" "}
        <a
          href="tel:+447949588127"
          className="text-primary underline hover:text-primary/80"
        >
          +44 7949 588127
        </a>
        .
      </p>

      {/* 3. Definitions */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        3. Definitions
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        In these Terms, the following definitions apply:
      </p>
      <ul className="mb-4 list-disc pl-6">
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong>&quot;Service&quot;</strong> means the Metalyzi platform,
          including the website, web application, APIs, AI-powered analysis
          tools, reports, and any associated features or functionality provided
          by Metusa Property Ltd.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong>&quot;User&quot;</strong> (also referred to as
          &quot;you&quot; or &quot;your&quot;) means any individual or entity
          that accesses or uses the Service, whether as a registered account
          holder or as a visitor.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong>&quot;Account&quot;</strong> means a registered user account
          created on the Service, which provides access to features based on
          the selected Subscription plan.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong>&quot;Analysis&quot;</strong> or <strong>&quot;Report&quot;</strong>{" "}
          means any property investment analysis, PDF report, benchmark data,
          or other output generated by the Service based on data you provide or
          that is otherwise available through the platform.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong>&quot;Subscription&quot;</strong> means the paid or free plan
          selected by the User, which determines access to certain features,
          usage limits, and pricing as described on the Service.
        </li>
      </ul>

      {/* 4. Account Registration and Security */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        4. Account Registration and Security
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        To access certain features of the Service, you must register for an
        Account. When registering, you agree to:
      </p>
      <ul className="mb-4 list-disc pl-6">
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Be at least 18 years of age. By creating an Account, you represent
          and warrant that you are at least 18 years old and have the legal
          capacity to enter into these Terms.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Provide accurate, current, and complete information during
          registration and keep your Account information up to date at all
          times.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Maintain the confidentiality of your password and any other
          credentials used to access your Account. You are solely responsible
          for all activity that occurs under your Account.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Notify us immediately at{" "}
          <a
            href="mailto:contact@metalyzi.co.uk"
            className="text-primary underline hover:text-primary/80"
          >
            contact@metalyzi.co.uk
          </a>{" "}
          if you become aware of any unauthorised use of your Account or any
          other breach of security.
        </li>
      </ul>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        We reserve the right to suspend or terminate any Account that we
        reasonably believe has been compromised or is being used in violation of
        these Terms.
      </p>

      {/* 5. Service Description */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        5. Service Description
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Metalyzi provides an AI-powered property investment analysis platform.
        The Service enables Users to input property deal data and receive
        automated analysis, including but not limited to:
      </p>
      <ul className="mb-4 list-disc pl-6">
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          AI-generated property investment analysis based on the data you
          provide, including rental yield calculations, cash flow projections,
          and return on investment estimates.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Downloadable PDF reports summarising the analysis of individual
          property deals.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Benchmark comparisons against market averages and regional data to
          help contextualise individual deal metrics.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Dashboard features for tracking and managing multiple property deal
          analyses over time.
        </li>
      </ul>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        We may update, modify, or discontinue features of the Service at any
        time. We will endeavour to provide reasonable notice of any material
        changes.
      </p>

      {/* 6. NOT Financial Advice */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        6. Not Financial Advice
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        <strong>
          The Service does not constitute financial advice, investment advice,
          tax advice, legal advice, or any other form of regulated advice.
        </strong>{" "}
        Metalyzi is not authorised or regulated by the Financial Conduct
        Authority (FCA) and does not carry out any regulated activities within
        the meaning of the Financial Services and Markets Act 2000 (FSMA 2000).
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        All Analyses and Reports generated by the Service are for informational
        and educational purposes only. They are based on data you provide and
        publicly available information, and are generated using automated
        algorithms and artificial intelligence. The outputs should not be relied
        upon as the sole basis for any investment, financial, or purchasing
        decision.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        You should always seek independent professional advice from a suitably
        qualified and FCA-regulated financial adviser, solicitor, surveyor, or
        accountant before making any property investment decision. Past
        performance indicators and projections included in any Report do not
        guarantee future results. Property values can go down as well as up, and
        you may not recover the amount of your original investment.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        <strong>
          You acknowledge and agree that any investment decision you make is
          entirely at your own risk, and Metusa Property Ltd accepts no
          liability for any loss or damage arising from your reliance on
          information provided by the Service.
        </strong>
      </p>

      {/* 7. Subscription Plans and Payment */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        7. Subscription Plans and Payment
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Metalyzi offers several Subscription plans, each providing different
        levels of access and usage allowances. The current plans are:
      </p>
      <ul className="mb-4 list-disc pl-6">
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong>Free</strong> — Limited access to the Service at no cost,
          subject to usage restrictions as described on the pricing page.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong>Pay-Per-Deal</strong> — A one-off payment of &pound;15 per
          individual deal analysis, with no ongoing commitment.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong>Starter</strong> — &pound;29 per month, providing access to a
          set number of deal analyses and standard features.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong>Pro</strong> — &pound;79 per month, providing access to an
          increased number of analyses, advanced features, and priority support.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong>Unlimited</strong> — &pound;199 per month, providing
          unlimited deal analyses, all features, and the ability to use Reports
          for commercial purposes including resale.
        </li>
      </ul>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Subscription fees are billed in advance on a monthly recurring basis
        unless otherwise stated. All prices are quoted in British Pounds
        Sterling (GBP) and are inclusive of VAT where applicable. We reserve the
        right to change our pricing at any time, provided that we give you at
        least 30 days&apos; notice before any price increase takes effect on
        your Account.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        All payments are processed securely through Stripe, our third-party
        payment processor. By providing your payment details, you authorise
        Stripe to charge your chosen payment method for the applicable
        Subscription fees. We do not store your full payment card details on our
        servers. Your use of Stripe is subject to Stripe&apos;s own terms of
        service and privacy policy.
      </p>

      {/* 8. Free Trial and Cancellation */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        8. Free Trial and Cancellation
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        We may from time to time offer a free trial period for certain
        Subscription plans. If a free trial is offered, you will not be charged
        during the trial period. At the end of the trial, your Subscription will
        automatically convert to a paid plan unless you cancel before the trial
        expires.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        You may cancel your Subscription at any time through your Account
        settings or by contacting us at{" "}
        <a
          href="mailto:contact@metalyzi.co.uk"
          className="text-primary underline hover:text-primary/80"
        >
          contact@metalyzi.co.uk
        </a>
        . Upon cancellation, your Subscription will remain active until the end
        of the current billing period. You will not be charged for subsequent
        billing periods after cancellation. No partial refunds are given for
        unused portions of a billing period, except where required by law.
      </p>

      {/* 9. Refund Policy */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        9. Refund Policy
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Our full refund policy is set out on our{" "}
        <Link
          href="/refund-policy"
          className="text-primary underline hover:text-primary/80"
        >
          Refund Policy
        </Link>{" "}
        page. Under the Consumer Contracts (Information, Cancellation and
        Additional Charges) Regulations 2013, you have the right to cancel your
        Subscription within 14 days of the date of purchase (the
        &quot;cooling-off period&quot;) and receive a full refund, provided that
        you have not consumed or used any paid Analyses or Reports during that
        period. If you have requested that the Service begin during the
        cooling-off period and you subsequently exercise your right to cancel,
        you may be charged a proportionate amount for the services already
        provided up to the point of cancellation.
      </p>

      {/* 10. Intellectual Property */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        10. Intellectual Property
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        All content, features, and functionality of the Service, including but
        not limited to text, graphics, logos, icons, images, software, code,
        algorithms, data compilations, report templates, and the overall design
        and structure of the platform, are the exclusive property of Metusa
        Property Ltd or its licensors and are protected by United Kingdom and
        international copyright, trade mark, and other intellectual property
        laws.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        You retain all rights to the data and information you input into the
        Service (&quot;User Data&quot;). By using the Service, you grant Metusa
        Property Ltd a limited, non-exclusive, royalty-free licence to process
        your User Data solely for the purpose of providing the Service to you.
        We will not sell, share, or otherwise disclose your User Data to third
        parties except as described in our{" "}
        <Link
          href="/privacy-policy"
          className="text-primary underline hover:text-primary/80"
        >
          Privacy Policy
        </Link>
        .
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        You may not reproduce, distribute, modify, create derivative works of,
        publicly display, or otherwise exploit any part of the Service or its
        content without our prior written consent, except as expressly permitted
        by these Terms or by applicable law.
      </p>

      {/* 11. Acceptable Use */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        11. Acceptable Use
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        You agree to use the Service only for lawful purposes and in accordance
        with these Terms. You must not:
      </p>
      <ul className="mb-4 list-disc pl-6">
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Use any automated means, including bots, scrapers, or crawlers, to
          access, extract, or collect data from the Service without our prior
          written consent.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Attempt to reverse engineer, decompile, disassemble, or otherwise
          derive the source code or underlying algorithms of the Service.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Use the Service for any illegal, fraudulent, or unauthorised purpose,
          including but not limited to money laundering, fraud, or any activity
          that violates applicable law.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Resell, redistribute, sublicence, or commercially exploit any
          Analyses, Reports, or other outputs of the Service without being on
          the Unlimited Subscription plan, which expressly permits such use.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Interfere with or disrupt the integrity or performance of the Service,
          including by introducing malware, viruses, or other harmful code.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Share your Account credentials with any third party or allow multiple
          individuals to use a single Account, unless your Subscription plan
          expressly permits team access.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Use the Service in any manner that could damage, disable, overburden,
          or impair the Service or interfere with any other party&apos;s use of
          the Service.
        </li>
      </ul>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        We reserve the right to investigate and take appropriate action,
        including suspension or termination of your Account, if we reasonably
        believe you have violated these acceptable use provisions.
      </p>

      {/* 12. Data Protection */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        12. Data Protection
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        We take the protection of your personal data seriously. Our collection,
        use, and storage of your personal information is governed by our{" "}
        <Link
          href="/privacy-policy"
          className="text-primary underline hover:text-primary/80"
        >
          Privacy Policy
        </Link>
        , which forms part of these Terms. By using the Service, you consent to
        the collection and processing of your data as described in our Privacy
        Policy.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        We process personal data in accordance with the UK General Data
        Protection Regulation (UK GDPR) and the Data Protection Act 2018. For
        full details on your rights as a data subject, including your rights to
        access, rectify, erase, restrict processing, data portability, and
        object to processing, please refer to our{" "}
        <Link
          href="/privacy-policy"
          className="text-primary underline hover:text-primary/80"
        >
          Privacy Policy
        </Link>
        .
      </p>

      {/* 13. Limitation of Liability */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        13. Limitation of Liability
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        To the maximum extent permitted by applicable law:
      </p>
      <ul className="mb-4 list-disc pl-6">
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          The Service is provided on an &quot;as is&quot; and &quot;as
          available&quot; basis without warranties of any kind, whether express
          or implied, including but not limited to implied warranties of
          merchantability, fitness for a particular purpose, and
          non-infringement.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Metusa Property Ltd shall not be liable for any indirect, incidental,
          special, consequential, or punitive damages, including but not limited
          to loss of profits, loss of data, loss of goodwill, or loss arising
          from any investment decision made in reliance on information provided
          by the Service.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Our total aggregate liability to you for any and all claims arising
          out of or in connection with the Service shall be limited to the total
          amount of fees paid by you to Metusa Property Ltd in the twelve (12)
          months immediately preceding the event giving rise to the claim.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          We do not guarantee the accuracy, completeness, or reliability of any
          Analysis, Report, or other output generated by the Service. You
          acknowledge that AI-generated outputs may contain errors and should be
          independently verified before acting upon them.
        </li>
      </ul>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        <strong>
          Nothing in these Terms excludes or limits our liability for death or
          personal injury caused by our negligence, for fraud or fraudulent
          misrepresentation, or for any other liability that cannot be excluded
          or limited under applicable law.
        </strong>
      </p>

      {/* 14. Indemnification */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        14. Indemnification
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        You agree to indemnify, defend, and hold harmless Metusa Property Ltd,
        its directors, officers, employees, agents, and affiliates from and
        against any and all claims, liabilities, damages, losses, costs, and
        expenses (including reasonable legal fees) arising out of or in
        connection with: (a) your use of the Service; (b) your breach of these
        Terms; (c) your violation of any applicable law or regulation; (d) any
        investment or financial decision you make based on information obtained
        through the Service; or (e) any dispute between you and a third party
        relating to your use of the Service.
      </p>

      {/* 15. Termination */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        15. Termination
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        We may suspend or terminate your Account and access to the Service
        immediately, without prior notice or liability, if we reasonably believe
        that you have breached these Terms, engaged in fraudulent or illegal
        activity, or if we are required to do so by law.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        You may cancel your Account and terminate these Terms at any time by
        contacting us at{" "}
        <a
          href="mailto:contact@metalyzi.co.uk"
          className="text-primary underline hover:text-primary/80"
        >
          contact@metalyzi.co.uk
        </a>{" "}
        or through your Account settings. Upon termination, your right to use
        the Service will cease immediately. Any provisions of these Terms that
        by their nature should survive termination shall continue to apply,
        including but not limited to intellectual property provisions, limitation
        of liability, indemnification, and governing law.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Upon termination, we may retain your data for a reasonable period in
        accordance with our{" "}
        <Link
          href="/privacy-policy"
          className="text-primary underline hover:text-primary/80"
        >
          Privacy Policy
        </Link>{" "}
        and applicable law, after which it will be securely deleted.
      </p>

      {/* 16. Modifications to Terms */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        16. Modifications to Terms
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        We reserve the right to modify these Terms at any time. If we make
        material changes, we will provide at least 30 days&apos; notice by
        posting the updated Terms on the Service and, where practicable, by
        notifying you via the email address associated with your Account.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Your continued use of the Service after the effective date of any
        modifications constitutes your acceptance of the updated Terms. If you
        do not agree to the revised Terms, you must stop using the Service and
        cancel your Account before the changes take effect.
      </p>

      {/* 17. Governing Law */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        17. Governing Law
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        These Terms and any dispute or claim arising out of or in connection with
        them or their subject matter or formation (including non-contractual
        disputes or claims) shall be governed by and construed in accordance with
        the laws of England and Wales.
      </p>

      {/* 18. Dispute Resolution */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        18. Dispute Resolution
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        In the event of any dispute arising out of or in connection with these
        Terms, you agree to first attempt to resolve the matter informally by
        contacting us at{" "}
        <a
          href="mailto:contact@metalyzi.co.uk"
          className="text-primary underline hover:text-primary/80"
        >
          contact@metalyzi.co.uk
        </a>
        . We will make reasonable efforts to resolve any complaint or dispute
        within 30 days of receipt.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        If the dispute cannot be resolved informally, the courts of England and
        Wales shall have exclusive jurisdiction to settle any dispute or claim
        arising out of or in connection with these Terms. Nothing in this clause
        affects your statutory rights as a consumer, including your right to
        bring proceedings in the courts of the country in which you are
        domiciled.
      </p>

      {/* 19. Severability */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        19. Severability
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        If any provision of these Terms is held to be invalid, illegal, or
        unenforceable by a court of competent jurisdiction, the remaining
        provisions shall continue in full force and effect. The invalid or
        unenforceable provision shall be deemed modified to the minimum extent
        necessary to make it valid, legal, and enforceable, while preserving the
        original intent of the parties as closely as possible.
      </p>

      {/* 20. Entire Agreement */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        20. Entire Agreement
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        These Terms, together with our{" "}
        <Link
          href="/privacy-policy"
          className="text-primary underline hover:text-primary/80"
        >
          Privacy Policy
        </Link>{" "}
        and{" "}
        <Link
          href="/refund-policy"
          className="text-primary underline hover:text-primary/80"
        >
          Refund Policy
        </Link>
        , constitute the entire agreement between you and Metusa Property Ltd
        with respect to your use of the Service. These Terms supersede all prior
        and contemporaneous agreements, proposals, representations, and
        understandings, whether oral or written, between you and us regarding
        the Service.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        No failure or delay by us in exercising any right, power, or remedy
        under these Terms shall operate as a waiver of that right, power, or
        remedy.
      </p>

      {/* 21. Contact Us */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        21. Contact Us
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        If you have any questions, concerns, or complaints about these Terms or
        the Service, please contact us:
      </p>
      <ul className="mb-4 list-disc pl-6">
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong>Company:</strong> Metusa Property Ltd, trading as Metalyzi
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong>Address:</strong> 9D Worrall Street, Salford, Manchester, M5
          4TZ, United Kingdom
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong>Email:</strong>{" "}
          <a
            href="mailto:contact@metalyzi.co.uk"
            className="text-primary underline hover:text-primary/80"
          >
            contact@metalyzi.co.uk
          </a>
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong>Phone:</strong>{" "}
          <a
            href="tel:+447949588127"
            className="text-primary underline hover:text-primary/80"
          >
            +44 7949 588127
          </a>
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong>Website:</strong>{" "}
          <a
            href="https://www.metalyzi.co.uk"
            className="text-primary underline hover:text-primary/80"
            target="_blank"
            rel="noopener noreferrer"
          >
            www.metalyzi.co.uk
          </a>
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong>Company Number:</strong> 15651934 (registered in England and
          Wales)
        </li>
      </ul>
    </div>
  );
}
