import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer — Metalyzi",
};

export default function DisclaimerPage() {
  return (
    <div className="mx-auto max-w-4xl px-6 py-16">
      <h1 className="mb-8 text-3xl font-bold text-foreground">Disclaimer</h1>

      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Last updated: 4 April 2026
      </p>

      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        This disclaimer applies to all services, content, analysis, and
        information provided by{" "}
        <strong className="text-foreground">Metusa Property Ltd</strong>,
        trading as <strong className="text-foreground">Metalyzi</strong>{" "}
        (company number 15651934, registered in England and Wales), whose
        registered address is 9D Worrall Street, Salford, Manchester, M5 4TZ
        (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;, or
        &quot;Metalyzi&quot;). By using our website at{" "}
        <a
          href="https://www.metalyzi.co.uk"
          className="text-primary underline hover:text-primary/80"
          target="_blank"
          rel="noopener noreferrer"
        >
          www.metalyzi.co.uk
        </a>{" "}
        and any associated services, you acknowledge and agree to the terms of
        this disclaimer.
      </p>

      {/* 1. General Disclaimer */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        1. General Disclaimer
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Metalyzi is a property analysis platform that provides data-driven
        insights, metrics, and tools designed to assist users in evaluating
        property investment opportunities across the United Kingdom. The
        information presented on our platform is provided for general
        informational and educational purposes only.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Metalyzi does <strong className="text-foreground">not</strong> provide
        regulated financial advice as defined under the Financial Services and
        Markets Act 2000 (FSMA). Nothing on our platform should be construed as
        a personal recommendation, financial promotion, or an invitation or
        inducement to engage in investment activity within the meaning of section
        21 of the FSMA.
      </p>

      {/* 2. Not Financial Advice */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        2. Not Financial Advice
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Metusa Property Ltd is{" "}
        <strong className="text-foreground">not</strong> authorised or regulated
        by the Financial Conduct Authority (FCA). We do not hold any FCA
        permissions, and we are not listed on the FCA Register.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        All analysis, scores, ratings, verdicts (including but not limited to
        PROCEED, REVIEW, and AVOID designations), yield calculations, cash flow
        projections, capital growth estimates, and any other outputs generated by
        our platform are provided strictly for informational purposes. They do
        not constitute and should not be relied upon as:
      </p>
      <ul className="mb-4 ml-6 list-disc">
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Investment advice or recommendations
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Financial advice or financial promotions
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Tax advice or tax planning guidance
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Legal advice of any kind
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Professional property valuations or surveys
        </li>
      </ul>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        You should always seek independent financial, legal, and tax advice from
        appropriately qualified and regulated professionals before making any
        property investment decision. Any reliance you place on the information
        provided by Metalyzi is strictly at your own risk.
      </p>

      {/* 3. Data Accuracy */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        3. Data Accuracy and Completeness
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        While we strive to ensure the accuracy and reliability of the
        information presented on our platform, we utilise data from a variety of
        sources including, but not limited to, HM Land Registry, the Valuation
        Office Agency (VOA), the Office for National Statistics (ONS),
        artificial intelligence analysis, and user-provided information. We
        cannot and do not guarantee the accuracy, completeness, currency, or
        timeliness of any data, analysis, or output displayed on our platform.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Property markets are inherently volatile and subject to rapid change.
        Data may be delayed, incomplete, or may not reflect the most current
        market conditions. Property prices, rental values, interest rates,
        legislation, and market conditions can change at any time without notice.
        Historical data and trends do not guarantee future outcomes.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Information provided by users (such as purchase price, renovation costs,
        or rental estimates) is not independently verified by Metalyzi. The
        accuracy of any analysis is directly dependent on the accuracy of the
        inputs provided.
      </p>

      {/* 4. AI-Generated Content */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        4. AI-Generated Content
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Significant portions of the analysis, insights, area summaries, risk
        assessments, and recommendations presented on Metalyzi are generated
        using artificial intelligence technology, specifically Anthropic Claude.
        Users should be aware of the following important limitations:
      </p>
      <ul className="mb-4 ml-6 list-disc">
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          AI-generated outputs may contain errors, inaccuracies, or
          hallucinations (instances where the AI produces plausible but factually
          incorrect information).
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          AI models may rely on training data that is outdated and may not
          reflect the most current market conditions, legislation, or
          regulations.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          AI-generated verdicts (PROCEED, REVIEW, AVOID), scores, risk ratings,
          and projections are algorithmic estimates based on available data. They
          are not professional opinions and should not be treated as such.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          AI-generated content does not take into account your individual
          financial circumstances, risk tolerance, investment objectives, or
          personal situation.
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          AI outputs should be independently verified and should never be the
          sole basis for any investment decision.
        </li>
      </ul>

      {/* 5. No Guarantee of Returns */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        5. No Guarantee of Returns
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Past performance, historical data, and projected returns displayed on
        our platform are not reliable indicators of future results. Property
        investment carries inherent risks, and there is no guarantee that any
        investment will achieve its objectives or that you will receive a return
        on your investment.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Risks associated with property investment include, but are not limited
        to:
      </p>
      <ul className="mb-4 ml-6 list-disc">
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Loss of capital, including the possibility of losing your entire
          investment
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Void periods where the property is unoccupied and generating no rental
          income
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Unexpected maintenance, repair, or renovation costs
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Market downturns and declining property values
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Changes to interest rates, taxation, or government legislation
          affecting property investment
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Tenant default, non-payment of rent, or damage to property
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Illiquidity and the inability to sell a property quickly at a desired
          price
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Changes to planning, licensing, or regulatory requirements
        </li>
      </ul>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Any yield figures, cash flow projections, capital growth estimates, or
        return on investment calculations presented on our platform are
        hypothetical illustrations based on assumptions that may not materialise.
        Actual results may differ materially from any projections shown.
      </p>

      {/* 6. Third-Party Data and Links */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        6. Third-Party Data and Links
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Our platform incorporates data from third-party sources including, but
        not limited to, HM Land Registry, the Valuation Office Agency (VOA),
        the Office for National Statistics (ONS), Rightmove, Zoopla, and
        OnTheMarket. We are not responsible for the accuracy, completeness, or
        reliability of any third-party data.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Third-party data is provided &quot;as is&quot; and may be subject to its
        own terms of use, licensing conditions, and disclaimers. The inclusion
        of third-party data on our platform does not imply endorsement by, or
        affiliation with, any third-party provider.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Where our platform contains links to external websites or resources, we
        do not control and are not responsible for the content, privacy
        practices, or availability of those external sites. Accessing external
        links is entirely at your own risk.
      </p>

      {/* 7. Stamp Duty Calculations */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        7. Stamp Duty Land Tax (SDLT) Calculations
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Any Stamp Duty Land Tax (SDLT) calculations provided on our platform are
        estimates based on current published rates and standard assumptions. SDLT
        calculations may not account for all individual circumstances,
        including but not limited to:
      </p>
      <ul className="mb-4 ml-6 list-disc">
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          First-time buyer relief eligibility
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Additional property surcharges and their applicable conditions
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Non-resident buyer surcharges
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Corporate body surcharges
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Mixed-use property calculations
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Properties in designated disadvantaged areas
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          Transfers involving leasehold properties or shared ownership schemes
        </li>
      </ul>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        SDLT rates and thresholds are subject to change by the government at any
        time. You should always verify SDLT calculations with HM Revenue &amp;
        Customs (HMRC) or a qualified solicitor before relying on them for any
        transaction.
      </p>

      {/* 8. Professional Advice Recommended */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        8. Professional Advice Recommended
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Before making any property investment decision, we strongly recommend
        that you consult with the following independent, qualified
        professionals:
      </p>
      <ul className="mb-4 ml-6 list-disc">
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong className="text-foreground">
            A qualified financial adviser
          </strong>{" "}
          — authorised and regulated by the Financial Conduct Authority (FCA), who
          can provide personalised investment advice based on your individual
          circumstances, financial goals, and risk tolerance
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong className="text-foreground">A solicitor or conveyancer</strong>{" "}
          — to advise on legal matters including property searches, title checks,
          contract review, leasehold implications, and compliance with all
          applicable laws and regulations
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong className="text-foreground">A tax adviser or accountant</strong>{" "}
          — to advise on the tax implications of property investment including
          income tax, capital gains tax, SDLT, inheritance tax, and the use of
          corporate structures
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong className="text-foreground">
            A chartered surveyor (RICS-accredited)
          </strong>{" "}
          — to provide professional property valuations, building surveys,
          condition reports, and assessments of any structural or maintenance
          issues
        </li>
      </ul>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Metalyzi is not a substitute for professional advice. The cost of
        obtaining professional advice is significantly less than the potential
        losses that could arise from an uninformed investment decision.
      </p>

      {/* 9. Limitation of Liability */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        9. Limitation of Liability
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        To the fullest extent permitted by law, Metusa Property Ltd, its
        directors, officers, employees, agents, and affiliates shall not be
        liable for any direct, indirect, incidental, consequential, special, or
        exemplary damages arising out of or in connection with your use of, or
        inability to use, our platform or any information provided therein.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        This includes, without limitation, any losses arising from reliance on
        any analysis, score, verdict, projection, or other content provided on
        our platform, whether generated by AI or otherwise. We accept no
        liability for any investment decisions made based on information obtained
        from Metalyzi.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        Nothing in this disclaimer excludes or limits our liability for death or
        personal injury caused by our negligence, fraud or fraudulent
        misrepresentation, or any other liability that cannot be excluded or
        limited by English law.
      </p>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        For full details of our liability limitations and your rights, please
        refer to our{" "}
        <Link
          href="/terms-of-service"
          className="text-primary underline hover:text-primary/80"
        >
          Terms of Service
        </Link>
        .
      </p>

      {/* 10. Contact Us */}
      <h2 className="mb-4 mt-10 text-xl font-semibold text-foreground">
        10. Contact Us
      </h2>
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        If you have any questions about this disclaimer or require further
        clarification, please contact us:
      </p>
      <ul className="mb-4 ml-6 list-none">
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong className="text-foreground">Company:</strong> Metusa Property
          Ltd, trading as Metalyzi
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong className="text-foreground">Company Number:</strong> 15651934
          (registered in England and Wales)
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong className="text-foreground">Registered Address:</strong> 9D
          Worrall Street, Salford, Manchester, M5 4TZ
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong className="text-foreground">Email:</strong>{" "}
          <a
            href="mailto:contact@metalyzi.co.uk"
            className="text-primary underline hover:text-primary/80"
          >
            contact@metalyzi.co.uk
          </a>
        </li>
        <li className="mb-4 text-sm leading-relaxed text-muted-foreground">
          <strong className="text-foreground">Website:</strong>{" "}
          <a
            href="https://www.metalyzi.co.uk"
            className="text-primary underline hover:text-primary/80"
            target="_blank"
            rel="noopener noreferrer"
          >
            www.metalyzi.co.uk
          </a>
        </li>
      </ul>
    </div>
  );
}
